export const jobRoles = [
  "Software Developer",
  "Data Scientist",
  "UI/UX Designer",
  "DevOps Engineer",
  "Cybersecurity Analyst",
  "Cloud Engineer",
  "AI/ML Engineer",
  "Full Stack Developer",
  "Game Developer",
  "IT Support Specialist",
  "Civil Engineer",
  "Mechanical Engineer",
  "Electrical Engineer",
  "Aerospace Engineer",
  "Robotics Engineer",
  "Chemical Engineer",
  "Automotive Engineer",
  "Doctor (General Physician)",
  "Surgeon",
  "Pharmacist",
  "Registered Nurse",
  "Physiotherapist",
  "Medical Researcher",
  "Dentist",
  "Radiologist",
  "Product Manager",
  "Business Analyst",
  "Marketing Manager",
  "HR Manager",
  "Financial Analyst",
  "Operations Manager",
  "Sales Executive",
  "Graphic Designer",
  "Content Writer",
  "Video Editor",
  "Photographer",
  "Digital Marketer",
  "Social Media Manager",
  "Animator",
  "Copywriter",
  "Teacher",
  "Professor",
  "Research Scientist",
  "Academic Writer",
  "Educational Consultant",
  "Lawyer",
  "Judge",
  "Paralegal",
  "Police Officer",
  "Public Relations Specialist",
  "Chef",
  "Electrician",
  "Plumber",
  "Mechanic",
  "Fashion Designer",
];
